### ISSUE TITLE
Trouble in building and debugging 2.0

### ISSUE THREAD

**Issue by PatRuelle** [rbei-etas/busmaster#615] opened 2013-12-03 23:23 UTC
My previous experience was with Busmaster v1.7 and using VS2008. I downloaded v2.0 and noticed it required VS Express2012 which I added to my development environment. I could not build a release or busmaster_debug because it reported it could not locate UDS_Protocol.lib so I  removed "$(SolutionDir)/BIN/Libs/$(OutDir)UDS_Protocol.lib" from the project via link > All Options > Additional Options. I noticed that UDS_.. is intended in v2.1. I could then build release and  busmaster_debug. The  busmaster_debug required I do a 'build all' and then a 'build' (I don't know why). But now if I do F5 to debug I get FLEXRAY_ETAS_BOA is out of date and I allow it to rebuild. It rebuilds more than FLEXRAY_ETAS_BOA. Consistently I'm getting 'project out of date every time I go to debug Busmaster. Any suggestions/correction for this annoyance?

**Comment by RBEI-Prathiba** [comment] 2015-11-02 07:25
Hi,
Please check with latest version of BusMaster and let us know if the issue is reproducible

**Comment by RBEI-Prathiba** [comment] 2015-11-23 07:57
Duplicate to #616, hence closing the issue.
#616 will be used for further updates

**Closed by RBEI-Prathiba** 2015-11-23 07:57 UTC
Labels: 1.3 patch (defect), 3.3 low priority (EC3)
