### ISSUE TITLE
Long delay in Signal Watch Window, display is updated even after disconnecting

### ISSUE THREAD

**Issue by Bastelphilipp** [rbei-etas/busmaster#578] opened 2013-09-23 18:57 UTC
At high datarates (e. g. 1000 msg/s @ 500 kBit/s) the data displayed in the Signal Watch Window is delayed by several seconds or more. Even after disconnecting the hardware, the contents of the Signal Watch Window is still updated for quite a long time. This issue applied to V1.8 as well as V1.9. I am running a core i5 notebook under Windows 7.

**Comment by RBEI-busmaster** [comment] 2016-09-14 07:07
We couldn't reproduce the issue with latest version. Please check with latest BusMaster v3.0.0.

**Comment by RBEI-busmaster** [comment] 2016-10-25 09:34
Could you please check with the latest version and feedback if the issue still persists ?

**Comment by RBEI-busmaster** [comment] 2016-11-11 11:54
We couldn't reproduce the issue. Hence, closing the issue.

**Closed by RBEI-busmaster** 2016-11-11 11:54 UTC
Labels: 1.3 patch (defect), 3.2 medium priority (EC2)
